
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paymin
 */
public class Modul7_3 extends javax.swing.JFrame {

    /**
     * Creates new form Modul7_3
     */
    public Modul7_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfSisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btHitungKbs = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tfJari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnHitungBla = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPanjang = new javax.swing.JTextField();
        tfLebar = new javax.swing.JTextField();
        tfTinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnHitungBlk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 20, 130, 14);
        jPanel2.add(tfSisi);
        tfSisi.setBounds(20, 40, 140, 30);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(170, 50, 13, 14);

        btHitungKbs.setText("HITUNG");
        btHitungKbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungKbsActionPerformed(evt);
            }
        });
        jPanel2.add(btHitungKbs);
        btHitungKbs.setBounds(20, 90, 71, 23);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Masukkan Panjang Jari - Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 29, 136, 14);

        tfJari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJariActionPerformed(evt);
            }
        });
        jPanel3.add(tfJari);
        tfJari.setBounds(10, 60, 100, 30);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(120, 70, 40, 14);

        btnHitungBla.setText("HITUNG");
        btnHitungBla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungBlaActionPerformed(evt);
            }
        });
        jPanel3.add(btnHitungBla);
        btnHitungBla.setBounds(10, 100, 71, 23);

        jTabbedPane1.addTab("Bola", jPanel3);

        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Panjang :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 123, 14);

        jLabel3.setText("Masukkan Lebar    :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 70, 93, 14);

        jLabel4.setText("Masukkan Tinggi    :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 110, 110, 14);

        tfPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPanjangActionPerformed(evt);
            }
        });
        jPanel1.add(tfPanjang);
        tfPanjang.setBounds(140, 20, 80, 32);
        jPanel1.add(tfLebar);
        tfLebar.setBounds(140, 60, 80, 32);
        jPanel1.add(tfTinggi);
        tfTinggi.setBounds(140, 100, 80, 32);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 30, 13, 14);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 70, 13, 14);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 110, 13, 14);

        btnHitungBlk.setText("HITUNG");
        btnHitungBlk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungBlkActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitungBlk);
        btnHitungBlk.setBounds(280, 130, 73, 23);

        jTabbedPane1.addTab("Balok", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 89, 380, 200);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PROGRAM PENCARI VOLUME BANGUN RUANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 420, 22);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPanjangActionPerformed

    private void tfJariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJariActionPerformed

    private void btHitungKbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungKbsActionPerformed
        int sisi;
        sisi = Integer.parseInt(tfSisi.getText());
        int hasil=sisi*sisi*sisi;
        
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah :"
                    +hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                     JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btHitungKbsActionPerformed

    private void btnHitungBlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungBlaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(tfJari.getText());
        float hasil=(float) (4/3*3.14*jari*jari*jari);
        
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah :"
                    +hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                     JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnHitungBlaActionPerformed

    private void btnHitungBlkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungBlkActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(tfPanjang.getText());
        lebar = Integer.parseInt(tfLebar.getText());
        tinggi = Integer.parseInt(tfTinggi.getText());
        int hasil=panjang*lebar*tinggi;
        
        try {
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"
                    +hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                     JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungBlkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul7_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul7_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul7_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul7_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul7_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHitungKbs;
    private javax.swing.JButton btnHitungBla;
    private javax.swing.JButton btnHitungBlk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tfJari;
    private javax.swing.JTextField tfLebar;
    private javax.swing.JTextField tfPanjang;
    private javax.swing.JTextField tfSisi;
    private javax.swing.JTextField tfTinggi;
    // End of variables declaration//GEN-END:variables
}
