
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paymin
 */
public class UjiKebolehan extends javax.swing.JFrame {
    
    Double ti, bt, hl;
    String temp;

    /**
     * Creates new form UjiKebolehan
     */
    public UjiKebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        coba = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        tng = new javax.swing.JTextField();
        brt = new javax.swing.JTextField();
        view1 = new javax.swing.JTextField();
        view2 = new javax.swing.JTextField();
        view3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(184, 20, 90, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 70, 60, 14);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 110, 60, 14);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 150, 100, 20);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 190, 80, 20);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(50, 220, 90, 23);

        coba.setText("Coba Lagi");
        coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobaActionPerformed(evt);
            }
        });
        getContentPane().add(coba);
        coba.setBounds(170, 220, 100, 23);

        keluar.setText("Keluar");
        getContentPane().add(keluar);
        keluar.setBounds(290, 220, 90, 23);

        jLabel6.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 260, 190, 14);

        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 260, 34, 14);
        getContentPane().add(nm);
        nm.setBounds(140, 60, 200, 30);

        tng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tngActionPerformed(evt);
            }
        });
        getContentPane().add(tng);
        tng.setBounds(140, 100, 60, 30);
        getContentPane().add(brt);
        brt.setBounds(140, 140, 60, 30);
        getContentPane().add(view1);
        view1.setBounds(260, 250, 59, 30);
        getContentPane().add(view2);
        view2.setBounds(40, 300, 350, 30);
        getContentPane().add(view3);
        view3.setBounds(40, 340, 350, 30);

        jRadioButton1.setText("Wanita");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(150, 190, 90, 23);

        jRadioButton2.setText("Pria");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(250, 190, 120, 23);

        setBounds(0, 0, 444, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void tngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tngActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        if(brt.getText().equals("")||tng.getText().equals("")
                ||nm.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Kotak isian belum diisi");
        } else if (jRadioButton1.isSelected()||jRadioButton2.isSelected()){
                try{
                    Proses();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
                }
        } else {
             JOptionPane.showMessageDialog(null, "Jenis kelamin kosong");
         }
    }//GEN-LAST:event_hitungActionPerformed

    private void cobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobaActionPerformed
        // TODO add your handling code here:
        nm.setText("");
        tng.setText("");
        brt.setText("");
        view1.setText("");
        view2.setText("");
        view3.setText("");
    }//GEN-LAST:event_cobaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UjiKebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UjiKebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton coba;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField tng;
    private javax.swing.JTextField view1;
    private javax.swing.JTextField view2;
    private javax.swing.JTextField view3;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
       ti = Double.valueOf(tng.getText());
       bt = Double.valueOf(brt.getText());
       
       if (jRadioButton1.isSelected()){
           hl = (ti - 100) * 1;
       } else if (jRadioButton2.isSelected()){
           hl = (ti - 104) * 1;
       }
       temp = Double.toString(hl.intValue());
       
       if (hl < bt){
           view1.setText(temp);
           view2.setText("Maaf " + nm.getText() + ", Sepertinya anda Overweight :(");
           view3.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
       } else if (hl > bt){
           view1.setText(temp);
           view2.setText("Maaf " + nm.getText() + ", Sepertinya anda Underweight :(");
           view3.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
       } else{
           view1.setText(temp);
           view2.setText("Maaf" + nm.getText() + ", Berat badan anda sudah ideal :)");
           view3.setText("Lanjutkan pola makan teratur dan gaya hidup sehat");
       }
    }
}
